version: '3.8'  

services:  
  app:  
    build: .  
    ports:  
      - "8080:8080"  
    environment:  
      - DB_HOST=localhost  
      - DB_PORT=5432  
      - DB_USER=postgres  # Replace with your database username  
      - DB_PASS=Superman  # Replace with your database password  
      - DB_NAME=PostgreSQL 17  # Replace with your database name  
    depends_on:  
      - db  
  
  db:  
    image: postgres:13  
    environment:  
      - POSTGRES_USER=your_db_user  # Replace with your database username  
      - POSTGRES_PASSWORD=your_db_password  # Replace with your database password  
      - POSTGRES_DB=your_db_name  # Replace with your database name  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  

volumes:  
  postgres_data:  