database:  
  host: localhost  
  port: 5432  
  user: your_db_user  # Replace with your database username  
  password: your_db_password  # Replace with your database password  
  name: your_db_name  # Replace with your database name  