database:  
  host: localhost  
  port: 8084  
  user: admin  # Replace with your database username  
  password: myNewP@ssw0rd  # Replace with your database password  
  name: videoads  # Replace with your database name  